/** @typedef {object} json
 * @property {string} name
 * @property {number} rating
 * @property {object[]} players
 * @property {string} players.name
 * @property {string} players.position
 * @property {string} players.rating
 * @property {object} players.skill
 * @property {string} players.skill.passing
 * @property {string} players.skill.shooting
 * @property {string} players.skill.tackling
 * @property {string} players.skill.saving
 * @property {string} players.skill.agility
 * @property {string} players.skill.strength
 * @property {string} players.skill.penalty_taking
 * @property {string} players.skill.jumping
 * @property {number[]} players.currentPOS
 * @property {number} players.fitness
 * @property {boolean} players.injured
 */
